import Header from '@/components/UI/Layout/Header';
import './globals.css';
import type { Metadata } from 'next';
import { Inter, Fira_Code } from 'next/font/google';
import Footer from '@/components/UI/Layout/Footer';

const fira = Fira_Code({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body
				className={
					fira.className +
					' shadow-body p-0 m-10 bg-primary-dark-blue h-[calc(100vh-80px)] rounded-lg flex flex-col'
				}
			>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
